default:
  image: node:18.16.0-alpine 


stages:
  - unit-tests
  - api
  - ui


before_script: 
  - apk add --no-cache sudo curl build-base g++ libpng libpng-dev jpeg-dev pango-dev cairo-dev giflib-dev python3 firefox
  

unit-tests:
  stage: unit-tests
  script:
    - npm install mocha
    - npm install mochawesome --save-dev  
    - npm run test
  artifacts:
    paths:
      - reports/unit-report.js  
    expire_in: 3 days
    when: always  



api:
  stage: api
  script:
    - npm install mocha
    - npm install mochawesome --save-dev
    - npm --prefix api run test
  artifacts:
    paths:
    - reports/api-report.js
    expire_in: 3 days
    when: always 



ui:
  stage: ui
  script:
    - npm install mocha
    - npm install mochawesome --save-dev
    - npm --prefix wdio install wdio
    - npm --prefix wdio run wdio
    artifacts:
    paths:
      - reports/ui-report.js  
    expire_in: 3 days
    when: always    
